from __future__ import annotations

from .models import Finding


def terraform_snippet(finding: Finding) -> str:
    if finding.rule_id.startswith("IAM") or finding.source in {"IAM", "IAM Access Analyzer"}:
        return '''# Review draft: replace broad identity permissions with scoped policy
resource "aws_iam_policy" "least_privilege_review" {
  name        = "least-privilege-review-policy"
  description = "Draft remediation generated by aws-cloud-security-scanner"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["REPLACE_WITH_REQUIRED_ACTIONS"]
      Resource = ["REPLACE_WITH_SCOPED_ARNS"]
      Condition = {
        BoolIfExists = { "aws:MultiFactorAuthPresent" = "true" }
      }
    }]
  })
}
'''
    if finding.rule_id == "CT-001":
        return '''# Guardrail idea: monitor root usage and alert through EventBridge/SNS
resource "aws_cloudwatch_event_rule" "root_usage" {
  name        = "detect-root-account-usage"
  description = "Alert on root account API usage"
  event_pattern = jsonencode({
    detail = { userIdentity = { type = ["Root"] } }
  })
}
'''
    return "# No automatic Terraform remediation is safe for this finding. Use the report guidance."
